# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://matienzo.org
title: Mark A. Matienzo
subtitle:
author:
  name: Mark A. Matienzo
  twitter: anarchivist
  picture: /images/matienzo.jpg
  url: http://matienzo.org
lang: en-US
simple_search: http://google.com/search
#description: Thoughts on recordkeeping, technology, and politics

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

feed:
  path: atom.xml
email: mark@matienzo.org

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
#root: /
permalink: /:year/:title/
#source: source
destination: _site
category_dir:
markdown: kramdown
highlighter: rouge

exclude:
  - bin/deploy
  - Gemfile
  - Gemfile.lock
  - rsync-exclude
  - config.rb


paginate: 10          # Posts per page on the blog index
paginate_path: "blog/page/:num"
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "More &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: <!--more-->

titlecase: false       # Converts page and post titles to titlecase

theme: jekyll-theme-basically-basic

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Begin config for Basically Basic
twitter_username: anarchivist
github_username: anarchivist
google_analytics: UA-6399155-1
disqus:
  shortname: matienzo
# End config for Basically Basically

# Begin config for Jekyll SEO tag
twitter:
  username: anarchivist
social:
  name: Mark A. Matienzo
  links:
    - https://twitter.com/anarchivist
    - https://github.com/anarchivist
    - https://keybase.io/anarchivist
    - https://linkedin.com/in/markmatienzo
    - https://orcid.org/0000-0003-3270-1306
