[context.production.environment]
  JEKYLL_ENV = "production"
  SUPERFEEDR_USERNAME = "anarchivist"

[build]
  functions = "functions"

[build.environment]
  TZ = "America/Los_Angeles"
  HUGO_VERSION = "0.73.0"
