backend:
  name: github
  repo: anarchivist/matienzo.org
  branch: master
media_folder: images
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Location
        name: location
        widget: object
        required: false
        fields:
          - label: Name
            name: name
            widget: string
            required: false
          - label: URL
            name: url
            widget: string
            required: false
          - label: Locality
            name: locality
            widget: string
            required: false
          - label: Region
            name: region
            widget: string
            required: false
          - label: Country
            name: country-code
            widget: string
            required: false
      - label: Bookmark of
        name: bookmark-of
        widget: list
        required: false
        field:
          - label: Name
            name: name
            widget: string
          - label: URL
            name: url
            widget: string
      - label: Categories
        name: tags
        widget: list
        required: false
      - label: Syndicated at
        name: syndication
        widget: list
        required: false
        field:
          - label: URL
            widget: text
      - label: content
        name: body
        widget: markdown
  - name: "notes"
    label: "Notes"
    folder: "_notes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Slug # This is a nasty workaround for netlify/netlify-cms#445
        name: title
        widget: string
        required: false
      - label: Date
        name: date
        widget: datetime
      - label: Bookmark of
        name: bookmark-of
        widget: list
        required: false
        field:
          - label: name
            name: name
            widget: string
          - label: URL
            name: url
            widget: string
      - label: content
        name: body
        widget: markdown
      - label: Location
        name: location
        widget: object
        required: false
        fields:
          - label: Name
            name: name
            widget: string
            required: false
          - label: URL
            name: url
            widget: string
            required: false
          - label: Locality
            name: locality
            widget: string
            required: false
          - label: Region
            name: region
            widget: string
            required: false
          - label: Country
            name: country-code
            widget: string
            required: false
      - label: Categories
        name: tags
        widget: list
        required: false
      - label: Syndicated at
        name: syndication
        widget: list
        required: false
        field:
          - label: URL
            widget: text
